---
  - name: Create directory
    ansible.builtin.file:
      path: /home/backup/mysql 
      state: directory 
      mode: 0775 
      owner: "{{ backup_user }}"
      group: "{{ backup_user }}" 

  - name: Create SQL user "backup" on SQL
    community.mysql.mysql_user: 
      name: "{{ backup_user }}"
      password: "{{ backup_password }}"
      priv: "{{ mysql_database }}.*:SELECT,LOCK TABLES"
      login_unix_socket: /var/run/mysqld/mysqld.sock 
      host: "localhost"
    no_log: True
    
  - name: Copy .my.cnf file 
    ansible.builtin.template: 
      src: ../templates/.my.cnf
      dest: /home/backup/.my.cnf 
      owner: "{{ backup_user }}"
      group:  "{{ backup_user }}"
      mode: 0775
    no_log: True

  - name: Create mysql-backup file 
    ansible.builtin.template: 
      src: ../templates/mysql-backup.j2
      dest: /etc/cron.d/mysql-backup
      owner: root 
      group: root 
      mode: 0775

  - name: Enable Cron
    service:
      name: cron
      state: started
      enabled: yes