- name: Install nginx
  apt:
    name: nginx

- name: Install index.html
  template:
    src: index.j2
    dest: /var/www/html/index.html

- name: Copy default.j2 
  template:
    src: default.j2 
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart nginx

- name: Enable nginx
  service:
    name: nginx 
    state: started
    enabled: yes