---
  - name: Create directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
    loop:
      - /opt/grafana/provisioning/dashboards
      - /opt/grafana/provisioning/datasources

  - name: grafana config
    ansible.builtin.template:
      src: grafana.ini.j2
      dest: /opt/grafana/grafana.ini
    no_log: True
    notify: Restart grafana docker

  - name: default grafana datasource
    ansible.builtin.template:
      src: datasource.yaml
      dest: /opt/grafana/provisioning/datasources/default.yaml
    notify: Restart grafana docker

  - name: default grafana dashboard
    ansible.builtin.template:
      src: dashboard.yaml
      dest: /opt/grafana/provisioning/dashboards/default.yaml
    notify: Restart grafana docker

  - name: dashboard jsons
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
    no_log: True
    loop:
      - main.json
      - mysql.json
      - syslog.json
      - pinger.json
    notify: Restart grafana docker

  - name: Docker Container
    community.docker.docker_container:
      container_default_behavior: no_defaults
      name: grafana
      image: grafana/grafana:8.3.3
      published_ports: "{{ grafana_port }}:3000"
      volumes: /opt/grafana:/etc/grafana
      restart_policy: always
    