- name: Grafana APT key
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Grafana Repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install Grafana
  apt: 
    name: grafana 

- name: Grafana Init Config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: Grafana Dashboard Setting
  template:
    src: dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart Grafana

- name: Grafana Datasource Setting
  template:
    src: datasource.yaml.j2
    dest: /etc/grafana/provisioning/datasources/default.yaml
  notify: Restart Grafana

- name: Create Grafana Dashboards Json Folder
  file:
    path: /etc/grafana/provisioning/dashboard-jsons
    state: directory
    group: grafana

- name: Main Dashboard Json
  copy:
    src: "../files/{{item}}"
    dest: /etc/grafana/provisioning/dashboard-jsons/{{item}}
    group: grafana
  loop:
    - main.json 
    - mysql.json

- name: Enable Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
  