- name: Install grafana requirement
  ansible.builtin.apt:
    name:
      - adduser
      - libfontconfig1

- name: dpkg grafana
  ansible.builtin.apt:
    deb: https://dl.grafana.com/enterprise/release/grafana-enterprise_8.2.3_amd64.deb
  notify: install admin key

- name: grafana config
  template:
    src: ../templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart grafana

- name: start and enable grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: grafana dashboard dir
  file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: grafana dashboard setting
  copy:
    src: ../files/main.json
    dest: /var/lib/grafana/dashboards/main.json
