- name: Install uwsgi
  apt:
    name: uwsgi
    install-recommends: yes

- name: Install uwsgi-core
  apt:
    name: uwsgi-core
    install-recommends: yes

- name: Install uWSGI python plugin
  apt:
    name: uwsgi-plugin-python3
    
- name: Add uWSGI config
  ansible.builtin.copy:
    src: ~/ica0002/ica0002/roles/uwsgi/files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: u=rwx,g=rwx,o=r
  notify: Restart uwsgi
      
- name: start uWSGI unconditionally
  ansible.builtin.service:
    name: uwsgi 
    enabled: yes