- name: Install uwsgi packages
  apt:
    name:
      - uwsgi
      - uwsgi-core
      - uwsgi-plugin-python3
      - python3-pymysql
    install-recommends: yes

- name: Create a directory
  file:
    path: /etc/uwsgi/apps-enabled
    state: directory

- name: agama.ini
  template: 
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    owner: agama
    mode: u=rwx,g=rwx,o=r
  notify:
    - Restart uwsgi

- name: Enable uwsgi
  service:
    name: uwsgi 
    state: started
    enabled: yes