- name: Install uwsgi packages
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3

- name: agama.ini
  template: 
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify:
    - Restart uwsgi

- name: Enable uwsgi
  service:
    name: uwsgi 
    state: started
    enabled: yes