- name: Default
  hosts: all
  roles: 
    - init
    - users
  become: yes

- name: Bind9
  hosts: dns_servers
  roles:
    - bind
  become: yes
  tags: dns

- name: dns
  hosts: all
  roles:
    - dns 
  become: yes 
  tags: dns

- name: Database server 
  hosts: db_servers
  roles: 
    - mysql
  become: yes

- name: Web Server
  hosts: web_servers
  roles: 
    - agama
    - uwsgi
    - nginx
  become: yes