- name: Default
  hosts: all
  roles: 
    - init
    - users
  become: yes

- name: Node-Exporter
  hosts: all 
  roles:
    - exporter_node
  become: yes
  tags: prometheus

- name: Bind9
  hosts: dns_servers
  roles:
    - bind
  become: yes
  tags: dns

- name: DNS
  hosts: all
  roles:
    - dns 
  become: yes 
  tags: dns

- name: Database server 
  hosts: db_servers
  roles: 
    - mysql
  become: yes

- name: Web Server
  hosts: web_servers
  roles: 
    - agama
    - uwsgi
  become: yes

- name: Nginx
  hosts: all
  roles:
    - nginx
  become: yes
  tags: prometheus

- name: Prometheus
  hosts: prometheus
  roles:
    - prometheus
  become: yes
  tags: prometheus