- name: Default
  hosts: all
  roles: 
    - init
    - users
  gather_facts: yes
  become: yes

- name: Node-Exporter
  hosts: all 
  roles:
    - exporter_node
  become: yes
  gather_facts: no
  tags: prometheus

- name: Bind9
  hosts: dns_servers
  roles:
    - bind
    - exporter_bind
  become: yes
  gather_facts: no
  tags: dns

- name: DNS
  hosts: all
  roles:
    - dns 
  become: yes 
  gather_facts: no
  tags: dns

- name: Database Server 
  hosts: db_servers
  roles: 
    - mysql
    - exporter_mysql
  become: yes
  gather_facts: no

- name: Web Server
  hosts: web_servers
  roles: 
    - agama
    - uwsgi
  become: yes
  gather_facts: no

- name: Nginx
  hosts: all
  roles:
    - nginx
    - exporter_nginx
  become: yes
  gather_facts: no
  tags: 
    - prometheus
    - grafana

- name: Prometheus & Grafana
  hosts: prometheus
  roles:
    - prometheus
    - grafana
  become: yes
  gather_facts: no
  tags: 
    - prometheus
    - grafana
