- name: Default
  hosts: all
  roles: 
    - init
    - users
    - node_exporter
  gather_facts: yes
  become: yes

- name: Bind9
  hosts: dns_servers
  roles:
    - bind
    - bind_exporter
  become: yes
  gather_facts: no
  tags: dns

- name: DNS
  hosts: all
  roles:
    - dns 
  become: yes 
  gather_facts: no
  tags: dns

- name: Database Server 
  hosts: db_servers
  roles: 
    - mysql
    - mysql_exporter
  become: yes
  gather_facts: no

- name: Web Server
  hosts: web_servers
  roles: 
    - agama
    - uwsgi
  become: yes
  gather_facts: no

- name: Nginx
  hosts: all
  roles:
    - nginx
    - nginx_exporter
  become: yes
  gather_facts: no
  tags: 
    - prometheus
    - grafana

- name: Prometheus & Grafana
  hosts: prometheus
  roles:
    - prometheus
    - grafana
  become: yes
  gather_facts: no
  tags: 
    - prometheus
    - grafana
