- name: Default
  hosts: all
  roles: 
    - init
    - users
    - node_exporter
    - rsyslog
  gather_facts: yes
  become: yes
  tags: 
    - init
    - influx

- name: Backup
  hosts: all
  roles:
    - backup
  gather_facts: no 
  become: yes 
  tags:
   - backup

- name: DNS Bind9
  hosts: dns_servers
  roles:
    - bind
    - bind_exporter
  become: yes
  gather_facts: no
  tags: dns

- name: DNS Resolved
  hosts: all
  roles:
    - dns 
  become: yes 
  gather_facts: no
  tags: dns

- name: Database Server 
  hosts: db_servers
  roles: 
    - mysql
    - mysql_exporter
    - mysql_backup
  become: yes
  gather_facts: yes
  tags: 
    - mysql
    - webapp

- name: Web Server
  hosts: web_servers
  roles: 
    - agama
    - uwsgi
  become: yes
  gather_facts: yes
  tags:
    - webapp

- name: Nginx
  hosts: all
  roles:
    - nginx
    - nginx_exporter
  become: yes
  gather_facts: no
  tags: 
    - prometheus
    - grafana

- name: Influxdb
  hosts: influxdb  
  become: yes 
  gather_facts: no 
  roles:
    - influxdb 
    - pinger
    - influxdb_exporter
    - influxdb_backup
  tags: influx

- name: Prometheus & Grafana
  hosts: prometheus
  roles:
    - prometheus
    - grafana
  become: yes
  gather_facts: no
  tags:
    - prometheus

- name: Grafana 
  hosts: grafana
  roles:
    - grafana
  become: yes
  gather_facts: no
  tags: grafana