- name: Default
  hosts: all
  roles: 
    - init
    - users
  become: yes

- name: Database server 
  hosts: db_servers
  roles: 
    - mysql
  become: yes

- name: Web Server
  hosts: web_servers
  roles: 
    - agama
    - uwsgi
    - nginx
  become: yes