- name: Add user 'agama'
  ansible.builtin.user:
    name: agama

- name: Create directory agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    mode: u+wr,g=rw,o=r

- name: Update and upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install flask
  apt:
    name: python3-flask

- name: Install flask-sqlalchemy
  apt:
    name: python3-flask-sqlalchemy

- name: Install sqlite3
  apt:
    name: sqlite3

- name: Install amaga.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/
  

