- name: Restart Nginx Exporter
  service:
    name: prometheus-nginx-exporter
    state: restarted

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Reload Daemons
  shell: systemctl daemon-reload