- name: Install MySQL Exporter
  apt:
    name: prometheus-mysqld-exporter

- name: MySQL Exporter Config
  template:
    src: my.cnf.j2 
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: 0644
  notify: Restart MySQL Exporter
  no_log: True

- name: MySQL Exporter arg file
  template:
    src: mysql_exporter_arg.j2
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart MySQL Exporter

- name: Flush handlers once
  meta: flush_handlers

- name: Enable MySQL Exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes