- name: Install MySQL Exporter
  apt:
    name: prometheus-mysqld-exporter

- name: MySQL Exporter Config
  template:
    src: my.cnf.j2 
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: 0644
  notify: Restart MySQL Exporter
  no_log: True

- name: Flush handlers once
  meta: flush_handlers

- name: Enable MySQL Exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes