- name: Install mysql-server
  apt:
    name: mysql-server

- name: Start and enabled mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Add mysql override.cnf
  ansible.builtin.copy:
    src: ../files/override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: Install PyMySQL
  apt:
    name: python3-pymysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
