- name: Install mysql-server
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Start and enabled mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Add mysql override.cnf
  ansible.builtin.template:
    src: ../templates/override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart mysql

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add mysql exporter user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv:
      '*.*': 'PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add mysel replication user
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    host: "%"
    priv:
      "*.*:REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Make replit read-only
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
  - Reset MySQL source
  - Reset MySQL replica