---
  - name: Install Node Exporter
    ansible.builtin.apt:
      name: prometheus-node-exporter

  - name: Start and enable Node exporter
    service:
      name: prometheus-node-exporter
      state: started
      enabled: yes
