- name: Add user 'juri'
  user:
    name: juri
    shell: /bin/bash

- name: Add user 'roman'
  user:
    name: roman
    shell: /bin/bash

- name: Add SSH key for 'juri'
  authorized_key:
    user: juri
    key: https://github.com/hudolejev.keys
  no_log: true

- name: Add SSH key for 'roman'
  authorized_key:
    user: roman 
    key: https://github.com/romankuchin.keys
  no_log: true
    
