---
  - name: Install iptables 
    ansible.builtin.apt:
      name: iptables-persistent

  - name: Install rule
    ansible.builtin.template:
      src: ../templates/iptables.mangle
      dest: /etc/iptables/rules.v4

  - name: Load iptables
    community.general.iptables_state:
      path: /etc/iptables/rules.v4
      state: restored
      table: mangle
    async: "{{ ansible_timeout }}"
    poll: 0

  - name: Enable netfilter-persistent
    ansible.builtin.service:
      name: netfilter-persistent
      state: started
      enabled: yes

  - name: Enable iptable
    ansible.builtin.service:
      name: iptables
      state: started
      enabled: yes