---
  - name: Install prometheus
    ansible.builtin.apt:
      name: prometheus

  - name: Copy prometheus config
    ansible.builtin.template:
      src: ../templates/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
    notify:
      - Restart prometheus

  - name: Copy prometheus default ARG
    ansible.builtin.template:
      src: ../templates/prometheus.j2
      dest: /etc/default/prometheus
    notify:
      - Restart prometheus

  - name: Enable prometheus
    ansible.builtin.service:
      name: prometheus
      enabled: yes
      state: started