---
  - name: Install docker
    ansible.builtin.apt:
      name:
        - docker.io
        - python3-docker
    
  - name: Enable docker 
    ansible.builtin.service:
      name: docker 
      state: started 
      enabled: yes 
    
  - name: Login to the docker hub
    community.docker.docker_login:
      username: keisukejpn
      password: "{{docker_password}}"
    no_log: True