---
  - name: Install bind9 and dnspython
    ansible.builtin.apt:
      name: 
        - bind9
        - python3-dnspython 

  - name: Option config 
    ansible.builtin.template:
      src: named.conf.options.j2
      dest: /etc/bind/named.conf.options
    no_log: true
    notify:
      - Restart Bind9
      - rndc reload

  - name: DNS zone config 
    when: inventory_hostname in groups ['dns_master']
    ansible.builtin.template: 
      src: ../templates/db.noobmaster69.j2
      dest: /var/cache/bind/db.noobmaster69
      force: no
    notify:
      - Restart Bind9
      - rndc reload

  - name: Reverse DNS config
    when: inventory_hostname in groups ['dns_master']
    ansible.builtin.template:
      src: db.domain.reverse
      dest: /var/cache/bind/db.reverse
      force: no
    notify:
      - Restart Bind9
      - rndc reload

  - name: local DNS config
    ansible.builtin.template:
      src: named.conf.local.j2
      dest: /etc/bind/named.conf.local
    notify:
      - Restart Bind9
      - rndc reload
