---
  - name: Update APT cache
    ansible.builtin.apt:
      cache_valid_time: 86400

  - name: sudo name resolve
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: 'localhost {{ inventory_hostname }}'
      owner: root
      group: root 
      mode: '0644'