- name: Update APT cache
  apt:
    cache_valid_time: 86400

- name: Update CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20211000*

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: debian